### ISSUE TITLE
关于左滑加载更多数据的问题

### ISSUE THREAD

**Issue by snzang** [colin-phang/KLineChartDemo#1]
作者你好，看了你的简书博客后很受启发，但关于左滑加载数据后显示比例会改变的问题，我依然没有得到解决。我这边在setData后调用chart.setMaxVisibleValueCount(oldKLineDataCount);依然不能保证加载后的数据数量和之前的一致。请问作者具体是如何解决的呢？

**Comment by colin-phang** [comment]
chart.setVisibleXRange(100,100 );这个方法可以保证 显示数据数量都为100。

**Comment by colin-phang** [comment]
chart.setVisibleXRange(100,100 );这个方法可以保证 显示数据数量都为100。
